### ISSUE TITLE
Connecting with openvpn

### ISSUE THREAD

**Issue by jozsefmorrissey** [Fullaxx/biglybt#3]
Hi sorry if im missing something,

I am trying to help my brother setup your image, it works perfectly except when we try to execute with vpn config. I have set up a password file and it causes the docker to crash on startup. When I launch without the vpn config and try to connect via "openvpn --config my.opvn" the connection continuously fails (logs below). Do you have any idea what I am missing?

Just for clarification
Works
`docker run -d --cap-add=NET_ADMIN --device /dev/net/tun  --sysctl net.ipv6.conf.all.disable_ipv6=0  -e OVPNSLEEPTIME='9'  -e LOGFILE='mylog'  -v /srv/docker/biglybt/in:/in  -v /srv/docker/biglybt/out:/out  -v C:/biglybt/config:/config  -p 127.0.0.1:5901:5901  fullaxx/biglybt`

Doesn't Work
`docker run -d --cap-add=NET_ADMIN --device /dev/net/tun  --sysctl net.ipv6.conf.all.disable_ipv6=0  -e OVPNSLEEPTIME='9' -e OVPNCFG='austria-udp.ovpn'  -e LOGFILE='mylog'  -v /srv/docker/biglybt/in:/in  -v /srv/docker/biglybt/out:/out  -v C:/biglybt/config:/config  -p 127.0.0.1:5901:5901  fullaxx/biglybt`

Thanks,
Jozsef

```
Sat Mar 14 05:37:51 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]23.227.192.103:4443
Sat Mar 14 05:37:51 2020 Attempting to establish TCP connection with [AF_INET]23.227.192.103:4443 [nonblock]
Sat Mar 14 05:38:12 2020 TCP: connect to [AF_INET]23.227.192.103:4443 failed: Connection refused
Sat Mar 14 05:38:12 2020 SIGUSR1[connection failed(soft),init_instance] received, process restarting
Sat Mar 14 05:38:52 2020 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Sat Mar 14 05:38:52 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]23.227.192.103:4443
Sat Mar 14 05:38:52 2020 Attempting to establish TCP connection with [AF_INET]23.227.192.103:4443 [nonblock]
Sat Mar 14 05:39:14 2020 TCP: connect to [AF_INET]23.227.192.103:4443 failed: Connection refused
Sat Mar 14 05:39:14 2020 SIGUSR1[connection failed(soft),init_instance] received, process restarting
Sat Mar 14 05:40:34 2020 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
.......
```

**Comment by Fullaxx** [comment]
Well, I have not experienced this myself, but this line in the log stands out:
TCP: connect to [AF_INET]23.227.192.103:4443 failed: Connection refused

for whatever reason it appears that the remote server rejected your attempt to connect.
maybe it doesn't like your openvpn profile or certificate?
Can you download a new one from your VPN provider?

**Comment by jozsefmorrissey** [comment]
Thanks for the speedy response, I was assuming that the certificates would work since they are being used on multiple computers. But maybe there was some sort of update that prevents registering old certificates with new devices.

Fingers crossed, thanks for your input,
Jozsef Morrissey

**Comment by Fullaxx** [comment]
No problem, if you have any more questions, feel free to open another issue.

Fullaxx

**Comment by jozsefmorrissey** [comment]
Did you have to do any network bridging for docker?

**Comment by Fullaxx** [comment]
No, in my setup I used all the commands listed in the readme.
openvpn connects normally, but everyone's setup could be different,
so you might try adding "--netowrk host" to the docker command line and see if that makes a difference for you.

**Comment by Fullaxx** [comment]
Also, make sure that you check your openvpn log every time, to ensure that you know exactly which problem that you are troubleshooting.  During the course of creating all the scripting, I had multiple issues with openvpn.

Are you still getting TCP: connect to 23.227.192.103:4443 failed: Connection refused ?
