### ISSUE TITLE
Startup error with newest docker image

### ISSUE THREAD

**Issue by blehnen** [Fullaxx/biglybt#5]
I'm getting an error with the image that was just pushed yesterday.  Everything was working fine up until then.

"Error launching startup command: Failed to close file descriptor for child process (operation not permitted)."

Any ideas?

I'm using this image -

fullaxx/biglybt:latest

-thanks

**Comment by Fullaxx** [comment]
yeah, There is some weirdness with ubuntu:jammy and newer OSs requiring a specific seccomp configuration?
Please look here and let me know if this solves your problem...
If it does, I will post a special note on this project.

https://github.com/Fullaxx/ubuntu-desktop/blob/master/TROUBLESHOOTING.md

**Comment by blehnen** [comment]
That was it - all working now, thank you!
