### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by Snake883** [Fullaxx/biglybt#7]
The Java VM is constantly using a lot of CPU.  The container is also painfully slow.
![image](https://user-images.githubusercontent.com/8312560/225118618-a0b4d33f-93a2-4bde-a262-92fbceac6dcc.png)

Java 11.0.18 (64 bit)
  Ubuntu
/usr/lib/jvm/java-11-openjdk-amd64

SWT v4942r22, gtk/3.24.33, zoom=100, dpi=96
Linux v5.19.17-Unraid, amd64 (64 bit)
B3.3.0.0/4 az3

**Comment by Fullaxx** [comment]
Can you describe what BiglyBT was doing at the time this was taken?

**Comment by Fullaxx** [comment]
2 more questions:
Can you tell me how to re-create the issue?
Also, does it happen with v3.2.0.0?

docker pull fullaxx/biglybt:3.2.0.0

**Comment by Fullaxx** [comment]
If this is related to a configuration item, I'd be happy to change the defaults.
If BiglyBT was checking files, then this is normal behavior.
If it's a bug, then it should be relayed to the developers of BiglyBT.

If your CPUs are pegged, then the user experience will suffer, there is nothing I can do about that.
You might consider using another torrent client if this behavior becomes routine.
I switched to QBitTorrent a long time ago.
https://github.com/Fullaxx/qbittorrent
I prefer it to BiglyBT.
